index:
  path: /jarvis/
  controller: Index:index

discordAuth:
  path: /jarvis/discord-auth
  controller: Discord:authPage

postUserData:
  path: /jarvis/postUserData
  controller: Discord:postUserData

logout:
  path: /jarvis/logout
  controller: Discord:logout

dashboard:
  path: /jarvis/dashboard
  controller: Dashboard:dashboard

dashboard_server:
  path: /jarvis/dashboard/server/{server}
  controller: Dashboard:serverDashboard
